<h1>Data Preprocessing</h1>

In [4]:
import pandas as pd
import numpy as np 

data = {'one':pd.Series([1,2,5],index = ['a','b','e']),
        'two':pd.Series([1,2,3,4],index = ['a','b','c','d'])}
table = pd.DataFrame(data)
print(table)

   one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN


In [13]:
from sklearn.impute import SimpleImputer
im=SimpleImputer(missing_values=np.nan, strategy = 'mean')
im.fit(table) #just calulates the mean
imputed_data=im.transform(table.values) #replaces the data into the table 
print(pd.DataFrame(imputed_data, columns = ['one','two']))

        one  two
0  1.000000  1.0
1  2.000000  2.0
2  2.666667  3.0
3  2.666667  4.0
4  5.000000  2.5


C:\Users\shukl\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


<h2>Handling the Caterogial Values</h2>

In [14]:
data1={'Customer_id':pd.Series([1,2,3,4,5]),
       'Loan_Type':pd.Series(['home_loan','Personal_Loan','Education_Loan','Home_Loan','Credit_Loan']),
       'Income':pd.Series(['30K','25K','15K','40K','35K'])}
loan_info = pd.DataFrame(data1)
print(loan_info)

   Customer_id       Loan_Type Income
0            1       home_loan    30K
1            2   Personal_Loan    25K
2            3  Education_Loan    15K
3            4       Home_Loan    40K
4            5     Credit_Loan    35K


In [19]:
#pd.get_dummies(loan_info)
pd.get_dummies(loan_info, prefix='abc',prefix_sep="*")

Customer_id  abc*Credit_Loan  abc*Education_Loan  abc*Home_Loan  \
0            1            False               False          False   
1            2            False               False          False   
2            3            False                True          False   
3            4            False               False           True   
4            5             True               False          False   

   abc*Personal_Loan  abc*home_loan  abc*15K  abc*25K  abc*30K  abc*35K  \
0              False           True    False    False     True    False   
1               True          False    False     True    False    False   
2              False          False     True    False    False    False   
3              False          False    False    False    False    False   
4              False          False    False    False    False     True   

   abc*40K  
0    False  
1    False  
2    False  
3     True  
4    False

<H2>Lable Encoder</H2>

In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
loan_info_upd=loan_info.apply(labelencoder.fit_transform)
print(loan_info_upd)

   Customer_id  Loan_Type  Income
0            0          4       2
1            1          3       1
2            2          1       0
3            3          2       4
4            4          0       3


<h2>OneHotEncoder</h2>


In [23]:
from sklearn.preprocessing import OneHotEncoder
obj=OneHotEncoder() #the true and false in the dummy is convered into 0s and 1s
x=obj.fit_transform(loan_info).toarray()
print(x)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


<h1>Trainning and Spliting Data</h1>

In [24]:
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris

In [25]:
iris = load_iris()

In [26]:
type(iris)

sklearn.utils._bunch.Bunch

In [ ]:
print(iris.DESCR)

In [36]:
X=iris.data
Y=iris.target

Y.shape

(150,)

In [37]:
X_train, X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2) # size of testing data is 20%
#the above function will return the input of testing data, training data and output of testing and tranning data
#randomly assigns the tranning and testing data

In [38]:
X_train.shape

(120, 4)

In [39]:
X_test.shape

(30, 4)